%% Copyright 2017
% Rita Chen richen@bu.edu
% Max Christ mmchrist@bu.edu
% Jillian Yong jeyong@bu.edu
% All Rights Reserved

%%
%Create title page

function HW2

% Create GUI background
GuiViewFig = figure( ...
   'Name','HW2', ...
   'NumberTitle','off', 'HandleVisibility', 'on', ...
   'tag', 'pLiverDisplay', 'Position', [100 200 800 600], ...
   'Visible','on', 'Resize', 'on',...
   'BusyAction','Queue','Interruptible','off', ...
   'Color', [.8 .8 .8], 'Pointer', 'arrow',...
   'DoubleBuffer', 'on','IntegerHandle', 'off', ...
   'Colormap', gray(256));


% Buttons
uicontrol('Style','Pushbutton','Units','normalized',...
    'Position',[.2 .5 .2 .1], 'BackgroundColor',[.8 .6 .9],...
    'String','Scatter Plot','FontSize', 18,'Callback','pLiverDisplay(''BrightenIm'')');
uicontrol('Style','Pushbutton','Units','normalized',...
    'Position',[.6 .5 .2 .1], 'BackgroundColor',[.6 .4 .7],...
    'String','Histogram','FontSize', 18, 'Callback','pLiverDisplay(''DarkenIm'')');

% Add a text uicontrol for user instructions
txt = uicontrol('Style','text',...
      'Units','normalized',...
      'Position',[.2 .7 .6 .05],...
      'BackgroundColor',[.8 .8 .8],...
      'FontSize', 18,...
      'String','Please select a button to display different figures.');
